language: python
python:
  - "3.6"
install:
  - pip install -r build_requirements.txt
  - pip install -r requirements.txt
script:
  - python -m unittest test_uc.py
  - python -m mypy uc.py
  - pylint --rcfile .pylintrc uc.py
  - ./.build-badges.sh
deploy:
  provider: gcs
  access_key_id: "Travis"
  secret_access_key: "AIzaSyD-TvRM8NKhilvBHZR10RgyArYnAAVFhN4"
  bucket: "undead-cubes-ci.storage.googleapis.com"
  skip_cleanup: true
  acl: public-read
  local-dir: .badges