language: python
python:
- '3.6'
install:
- pip install -r build_requirements.txt
- pip install -r requirements.txt
script:
- python -m unittest test_uc.py
- python -m mypy uc.py
- pylint --rcfile .pylintrc uc.py
- "./.build-badges.sh"
deploy:
  provider: gcs
  access_key_id: GOOGBH6KHIGVZ6FMANKZ
  secret_access_key:
    secure: ZJAV2SUZ20gJHhwkhPNFsV8dhxE68WO260kQSklQI4P35Rvi0IHWp5WjKfYTGBfUhCp46oIA1KLkLEoNA4Q+FR8b+zodLRumrvsxC5zU3wpsn7QyGWyyNPBLU8QkmX9IuOWpUWOdWQA0/16HHHHta+tyKyAbxNiCJzgfdG4/ObPs1GRthBPUwkrXy0wodIoDE9cIq6XFzVH7F7EbALP0q6cyU77YBdOK+gqK6hjSgrWYjXosN4wA9UnTojuxIOxpZ0BPs1jpb/O+tDWqpQ/IngUsiXAX+iYFWxaf/9Eyojgx7ftpWTYjvOHiy5OoHBvSTJrpDG94Nt+dnsybdphwLiKB72i1ib0i4B/zmCeizQxYQbHGklRLY2DXQH/f2eSWAgjdUfmSsi8nqWUN9m5PNIM7JRfJnhZjNOivx5OlYdXyg3dttSqXoWTpJVN8BKzcjMTl61IfwQlkG/2l+10qTlB5E8ESLNNyZ6v9AvW46ZJdBPsNHRXleZVPNgBwcItqR3FupD6UhwnWEtnaYWm4MVbMUnPNW2K3wlnGMhUDnQE1/TmjFPqoQfd77bWcXgF38SMeZNmkErpCsYI8zWkOSvVSXFmv7qqXViPq3oAJCy4ayQ35G6bG7/XwsnA1zgZA7uCxg8RidgSPw0k9f6xQUDv0UYSss9yf4CUOXuvuD7Y=
  bucket: undead-cubes-ci
  local-dir: ".badges"
  skip_cleanup: true
  on:
    repo: tomjsalmon/undeadcubes
